export const authenticateConstants = {
    UPDATE_USER_LIST: 'UPDATE_USER_LIST',
    GET_USER_LIST: 'GET_USER_LIST',
    LOGGEDIN_USER_DATA: 'LOGGEDIN_USER_DATA',
    LOGGEDOUT_USER_DATA: 'LOGGEDOUT_USER_DATA'
};